### ISSUE TITLE
Not published to npm

### ISSUE THREAD

**Issue by shaundon** [tipsi/tipsi-dash-line#5]
Hi - readme.md mentions that you can use `npm install --save tipsi-dash-line` to install this, but it doesn't appear to be uploaded to the registry: https://www.npmjs.com/package/tipsi-dash-line.

**Comment by vadermemo** [comment]
npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-S" "tipsi-dash-line"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/tipsi-dash-line
npm ERR! 404 
npm ERR! 404  'tipsi-dash-line' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/memo/Documents/workspaces/react-native/tacticalboard/npm-debug.log

**Comment by cybergrind** [comment]
@shaundon  @vadermemo  I've published it
